services:
  gradio-app:
    build:
      context: ./src/gradio
    depends_on:
      ollama:
        condition: service_started
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      gradio-app:
        condition: service_started
    restart: always
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama: {}

networks:
  app-network:
    driver: bridge
