services:
  gradio-app:
    build:
      context: ./src/gradio
    command: >
      --port 7860
      --log-level debug
    environment:
      OLLAMA_URL: http://ollama:11434
    depends_on:
      ollama:
        condition: service_started
    restart: always

  nginx:
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      gradio-app:
        condition: service_started
    restart: always

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped

volumes:
  ollama: {}
